file_format: "1"
id: corne_v3
name: Corne V3 (PAT912x + OLED)
type: shield
url: https://github.com/MNSerg/zmk-for-keys
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
  - pointing
  - studio
siblings:
  - corne_v3_left
  - corne_v3_left_bare
  - corne_v3_right
  - corne_v3_right_bare
  - corne_v3_right_nobtn
