file_format: "1"
id: corne
name: CORNE
type: shield
url: https://github.com/MNSerg/zmk-for-keys
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
  - pointing
siblings:
  - corne_left
  - corne_right
